### PR TITLE
protect user input

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement

my inputs are mutated.  this is unexpected.  i have need for my inputs as originally written in other parts of my code
# solution

clone inputs, don't mutate user input
# discussion

tests are currently broken in master.  this change is so darned simple i hope we can let it through anyway :), or get tests back up

### CODE REVIEW

**Comment by gr2m** [comment]
looks good, thanks :) 

Could you reword your commit to `fix: clone options to avoid mutation` please? The `fix: ...` prefix is significant, it will release a new patch version.

Unfortunately we have to fix the tests, because [the release process is automated](https://github.com/semantic-release/semantic-release), if tests are broken, no release ¯\_(ツ)_/¯

**Comment by cdaringe** [comment]
your test structure is a little foreign looking to me, and some guy with :+1: two thumbs :-1: has endless h/w to do :).  anyway, i did rebase and patch the commit :)

**Comment by gr2m** [comment]
looks like your change is what's breaking it, master is good, I could reprodue it locally. Did you run tests with `npm test`?

**Comment by cdaringe** [comment]
you're right--apologies on the false claim.  _they are working_ in master. hmmm

**Comment by gr2m** [comment]
what’s status on this? Do you want to investigate what’s breaking or can we close the PR?

**Comment by cdaringe** [comment]
i'm probably not going to come back to this.  i'm ok to close.  sorry, i definitely want to figure it out for everyone, i'm just overcommitted ATM!

**Pull request closed without merging**
