### PR TITLE
feat: use users's pouchdb-server if possible

### LINKED ISSUE #4: Include npm
Currently the path to the pouchdb-server bin [is hardcoded](https://github.com/gr2m/spawn-pouchdb-server/blob/master/index.js#L24).

But when used in a project which already includes pouchdb-server the dependency is not double installed and taken from there. Also, npm v3 has flat dependencies so it might break.

The solution is to [ask npm for the executable path](https://github.com/npm/npm#using-npm-programmatically). If in doubt, I'm sure @boennemann can help ;)

### PR DESCRIPTION
**Pull request by boennemann**
Should close #4.

Please verify @jo @gr2m

### CODE REVIEW

**Comment by gr2m** [comment]
I've tested it and had no issue, but it also worked before for me. @jo, can you please double check it, I couldn't reproduce the issue you had

**Comment by jo** [comment]
sure, will check asap

**Comment by jo** [comment]
I can confirm that it works and fixes #4 :+1:

**Comment by boennemann** [comment]
Nice :+1:

**Comment by gr2m** [comment]
Awesomesauce, thanks gentlemen!

**Comment by boennemann** [comment]
So when will this land on npm? Oh wait that's a thing of the past ❤

**Comment by gr2m** [comment]
hahahahaha king style :crown:

**Comment by jo** [comment]
<3ing you

**Pull request merged**
